export type Ciudad = {
  nombre: string;
  top: string;
  left: string;
  color: string;
};

export const ciudades: Ciudad[] = [
  { nombre: "Pal Park", top: "96%", left: "31.4%", color: "blue" },
  { nombre: "Twinleaf Town", top: "92%", left: "11.8%", color: "blue" },
  { nombre: "Sandgem Town", top: "88%", left: "18.5%", color: "blue" },
  { nombre: "Jubilife City", top: "77%", left: "16.6%", color: "blue" },
  { nombre: "Oreburgh City", top: "76%", left: "31.5%", color: "blue" },
  { nombre: "Floaroma Town", top: "60%", left: "18.5%", color: "blue" },
  { nombre: "Eterna City", top: "46.5%", left: "31.5%", color: "blue" },
  { nombre: "Eterna Forest", top: "47%", left: "23%", color: "blue" },
  { nombre: "Hearthome City", top: "68%", left: "49.5%", color: "blue" },
  { nombre: "Solaceon Town", top: "62.5%", left: "59.2%", color: "blue" },
  { nombre: "Veilstone City", top: "56.5%", left: "72%", color: "blue" },
  { nombre: "Pastoria City", top: "85.5%", left: "62.2%", color: "blue" },
  { nombre: "Celestic Town", top: "46%", left: "48.2%", color: "blue" },
  { nombre: "Canalave City", top: "73%", left: "5.2%", color: "blue" },
  { nombre: "Snowpoint City", top: "6.5%", left: "37.8%", color: "blue" },
  { nombre: "Sunyshore City", top: "77%", left: "88.5%", color: "blue" },
  { nombre: "Sinnoh League", top: "49.5%", left: "86.8%", color: "blue" },
  { nombre: "Fight Area", top: "33%", left: "65.5%", color: "blue" },
  { nombre: "Survival Area", top: "20%", left: "67.2%", color: "blue" },
  { nombre: "Resort Area", top: "37.6%", left: "83.6%", color: "blue" },
  { nombre: "Full Moon Island", top: "12.3%", left: "9%", color: "blue" },
  { nombre: "New Moon Island", top: "12.3%", left: "15%", color: "blue" },
  { nombre: "Flower Paradise", top: "5%", left: "93.3%", color: "blue" },
  { nombre: "Iron Island", top: "41.7%", left: "11.8%", color: "blue" },
  { nombre: "Stark Mountain", top: "9%", left: "77%", color: "blue" },
  { nombre: "Mount Coronet", top: "58%", left: "39%", color: "blue" },
];

export const conexiones: { [ciudad: string]: string[] } = {
  "Pal Park": ["Twinleaf Town", "Sandgem Town"],
  "Twinleaf Town": ["Sandgem Town", "Pal Park"],
  "Sandgem Town": ["Twinleaf Town", "Jubilife City", "Pal Park"],
  "Jubilife City": [
    "Sandgem Town",
    "Oreburgh City",
    "Floaroma Town",
    "Canalave City",
  ],
  "Oreburgh City": [
    "Jubilife City",
    "Mount Coronet",
    "Eterna City",
    "Hearthome City",
  ],
  "Floaroma Town": ["Jubilife City", "Eterna City", "Eterna Forest"],
  "Eterna Forest": ["Floaroma Town", "Eterna City"],
  "Eterna City": [
    "Eterna Forest",
    "Floaroma Town",
    "Celestic Town",
    "Mount Coronet",
    "Oreburgh City",
    "Snowpoint City",
  ],
  "Celestic Town": [
    "Eterna City",
    "Hearthome City",
    "Solaceon Town",
    "Oreburgh City",
    "Snowpoint City",
    "Veilstone City",
    "Mount Coronet",
  ],
  "Hearthome City": [
    "Celestic Town",
    "Solaceon Town",
    "Pastoria City",
    "Oreburgh City",
    "Mount Coronet",
    "Snowpoint City",
  ],
  "Solaceon Town": ["Hearthome City", "Veilstone City", "Celestic Town"],
  "Veilstone City": [
    "Solaceon Town",
    "Pastoria City",
    "Sunyshore City",
    "Celestic Town",
    "Resort Area",
  ],
  "Pastoria City": ["Hearthome City", "Veilstone City", "Sunyshore City"],
  "Sunyshore City": ["Pastoria City", "Veilstone City", "Sinnoh League"],
  "Sinnoh League": ["Sunyshore City", "Resort Area"],
  "Canalave City": ["Jubilife City"],
  "Snowpoint City": ["Eterna City", "Celestic Town", "Mount Coronet"],
  "Fight Area": ["Survival Area", "Resort Area"],
  "Survival Area": ["Fight Area", "Resort Area", "Stark Mountain"],
  "Resort Area": [
    "Fight Area",
    "Sinnoh League",
    "Survival Area",
    "Stark Mountain",
    "Veilstone City",
  ],
  "Mount Coronet": [
    "Oreburgh City",
    "Eterna City",
    "Celestic Town",
    "Hearthome City",
    "Mount Coronet",
    "Snowpoint City",
  ],
  "Iron Island": ["Full Moon Island", "New Moon Island", "Floaroma Town"],
  "Full Moon Island": ["Iron Island", "New Moon Island"],
  "New Moon Island": ["Iron Island", "Full Moon Island"],
  "Flower Paradise": ["Sinnoh League"],
  "Stark Mountain": ["Survival Area", "Resort Area"],
};
